
server:
  port: 1000
spring:
  datasource:
    url: jdbc:h2:mem:payment-service
    driverClassName: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true
        path: /h2
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true